-- Dummy weekly menu (Monday to Sunday) and 5 weeks of dated menus from it.
-- Run in the Supabase SQL Editor after the step 2 migration. Safe to re-run:
-- days you have already edited are left as they are.

insert into public.weekly_menu_items (weekday, meal_type, name, is_veg, position) values
  (1, 'breakfast', 'Poha', true, 0),
  (1, 'breakfast', 'Boiled egg', false, 1),
  (1, 'breakfast', 'Bread & butter', true, 2),
  (1, 'breakfast', 'Tea / Coffee', true, 3),
  (1, 'lunch', 'Rice', true, 0),
  (1, 'lunch', 'Dal tadka', true, 1),
  (1, 'lunch', 'Roti', true, 2),
  (1, 'lunch', 'Aloo gobhi', true, 3),
  (1, 'lunch', 'Salad', true, 4),
  (1, 'snacks', 'Samosa', true, 0),
  (1, 'snacks', 'Tea', true, 1),
  (1, 'dinner', 'Jeera rice', true, 0),
  (1, 'dinner', 'Rajma', true, 1),
  (1, 'dinner', 'Roti', true, 2),
  (1, 'dinner', 'Mix veg', true, 3),
  (1, 'dinner', 'Kheer', true, 4),
  (2, 'breakfast', 'Aloo paratha', true, 0),
  (2, 'breakfast', 'Curd', true, 1),
  (2, 'breakfast', 'Pickle', true, 2),
  (2, 'breakfast', 'Tea / Coffee', true, 3),
  (2, 'lunch', 'Rice', true, 0),
  (2, 'lunch', 'Sambar', true, 1),
  (2, 'lunch', 'Roti', true, 2),
  (2, 'lunch', 'Bhindi fry', true, 3),
  (2, 'lunch', 'Buttermilk', true, 4),
  (2, 'snacks', 'Bread pakoda', true, 0),
  (2, 'snacks', 'Tea', true, 1),
  (2, 'dinner', 'Rice', true, 0),
  (2, 'dinner', 'Dal makhani', true, 1),
  (2, 'dinner', 'Roti', true, 2),
  (2, 'dinner', 'Egg curry', false, 3),
  (2, 'dinner', 'Paneer butter masala', true, 4),
  (3, 'breakfast', 'Idli', true, 0),
  (3, 'breakfast', 'Sambar', true, 1),
  (3, 'breakfast', 'Coconut chutney', true, 2),
  (3, 'breakfast', 'Tea / Coffee', true, 3),
  (3, 'lunch', 'Veg pulao', true, 0),
  (3, 'lunch', 'Raita', true, 1),
  (3, 'lunch', 'Roti', true, 2),
  (3, 'lunch', 'Chole', true, 3),
  (3, 'lunch', 'Salad', true, 4),
  (3, 'snacks', 'Veg sandwich', true, 0),
  (3, 'snacks', 'Tea', true, 1),
  (3, 'dinner', 'Rice', true, 0),
  (3, 'dinner', 'Dal fry', true, 1),
  (3, 'dinner', 'Roti', true, 2),
  (3, 'dinner', 'Chicken curry', false, 3),
  (3, 'dinner', 'Soya chunks curry', true, 4),
  (3, 'dinner', 'Gulab jamun', true, 5),
  (4, 'breakfast', 'Upma', true, 0),
  (4, 'breakfast', 'Banana', true, 1),
  (4, 'breakfast', 'Bread & jam', true, 2),
  (4, 'breakfast', 'Tea / Coffee', true, 3),
  (4, 'lunch', 'Rice', true, 0),
  (4, 'lunch', 'Kadhi pakoda', true, 1),
  (4, 'lunch', 'Roti', true, 2),
  (4, 'lunch', 'Aloo matar', true, 3),
  (4, 'lunch', 'Papad', true, 4),
  (4, 'snacks', 'Maggi', true, 0),
  (4, 'snacks', 'Tea', true, 1),
  (4, 'dinner', 'Rice', true, 0),
  (4, 'dinner', 'Moong dal', true, 1),
  (4, 'dinner', 'Roti', true, 2),
  (4, 'dinner', 'Kadai paneer', true, 3),
  (4, 'dinner', 'Salad', true, 4),
  (5, 'breakfast', 'Chole bhature', true, 0),
  (5, 'breakfast', 'Tea / Coffee', true, 1),
  (5, 'lunch', 'Lemon rice', true, 0),
  (5, 'lunch', 'Dal', true, 1),
  (5, 'lunch', 'Roti', true, 2),
  (5, 'lunch', 'Cabbage sabzi', true, 3),
  (5, 'lunch', 'Curd', true, 4),
  (5, 'snacks', 'Kachori', true, 0),
  (5, 'snacks', 'Tea', true, 1),
  (5, 'dinner', 'Rice', true, 0),
  (5, 'dinner', 'Dal tadka', true, 1),
  (5, 'dinner', 'Roti', true, 2),
  (5, 'dinner', 'Egg bhurji', false, 3),
  (5, 'dinner', 'Mix veg', true, 4),
  (5, 'dinner', 'Ice cream', true, 5),
  (6, 'breakfast', 'Dosa', true, 0),
  (6, 'breakfast', 'Sambar', true, 1),
  (6, 'breakfast', 'Chutney', true, 2),
  (6, 'breakfast', 'Tea / Coffee', true, 3),
  (6, 'lunch', 'Veg biryani', true, 0),
  (6, 'lunch', 'Raita', true, 1),
  (6, 'lunch', 'Salan', true, 2),
  (6, 'lunch', 'Salad', true, 3),
  (6, 'snacks', 'Pav bhaji', true, 0),
  (6, 'snacks', 'Tea', true, 1),
  (6, 'dinner', 'Rice', true, 0),
  (6, 'dinner', 'Dal', true, 1),
  (6, 'dinner', 'Roti', true, 2),
  (6, 'dinner', 'Aloo jeera', true, 3),
  (6, 'dinner', 'Halwa', true, 4),
  (7, 'breakfast', 'Puri', true, 0),
  (7, 'breakfast', 'Aloo sabzi', true, 1),
  (7, 'breakfast', 'Jalebi', true, 2),
  (7, 'breakfast', 'Tea / Coffee', true, 3),
  (7, 'lunch', 'Chicken biryani', false, 0),
  (7, 'lunch', 'Veg biryani', true, 1),
  (7, 'lunch', 'Raita', true, 2),
  (7, 'lunch', 'Salad', true, 3),
  (7, 'snacks', 'Pakode', true, 0),
  (7, 'snacks', 'Tea', true, 1),
  (7, 'dinner', 'Khichdi', true, 0),
  (7, 'dinner', 'Kadhi', true, 1),
  (7, 'dinner', 'Papad', true, 2),
  (7, 'dinner', 'Pickle', true, 3)
on conflict (weekday, meal_type, name) do update
  set is_veg = excluded.is_veg, position = excluded.position;

-- Last 7 days (so ratings and history have something to show) through the next 4 weeks.
select public.apply_weekly_menu(public.today_ist() - 7, 35) as meals_filled;
